# syntax=docker/dockerfile:1.4

FROM {{ image.origin }}

ARG TARGETARCH

RUN apk add wget

RUN wget -O {{ upstream_file_name }} {{ upstream_file_url }} && \
    tar xzf {{ upstream_file_name }} && \
    mv AdGuardHome/AdGuardHome /usr/local/bin/AdGuardHome

{{ dockerfile_root | default('') }}

USER root

CMD ["/usr/local/bin/AdGuardHome", "-c", "/etc/adguard/config.yml"]
