---
- name: Daemon reload
  listen: Restart blackbox_exporter
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart blackbox_exporter
  listen: Restart blackbox_exporter
  ansible.builtin.service:
    name: blackbox_exporter
    state: restarted
    enabled: true
