---
- name: Create default directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "{{ software_path }}/config"

# - name: Copy configuration file
#   ansible.builtin.template:
#     src: configuration.yaml.j2
#     dest: "{{ software_path }}/config/configuration.yaml"
#     owner: root
#     group: root
#     mode: '0600'

- name: Copy nomad job to destination
  ansible.builtin.template:
    src: nomad.hcl
    dest: "/var/tmp/{{ domain }}.nomad"
    owner: root
    group: root
    mode: '0600'

- name: Run nomad job
  ansible.builtin.include_role:
    name: nomad
    tasks_from: job_run.yml
