---
ufw_ipv6: "yes"
ufw_default_input_policy: DROP
ufw_default_output_policy: ACCEPT
ufw_default_forward_policy: DROP
ufw_default_application_policy: SKIP
ufw_logging: "off"

ufw_state: enabled
ufw_reset: false

ufw_rules:
  - direction: in
    interface: docker0
    rule: allow
  - port: 22
    proto: tcp
    rule: allow
  - port: 80
    proto: tcp
    rule: allow
    direction: in
  - port: 80
    proto: tcp
    rule: allow
    direction: out
  - port: 443
    proto: tcp
    rule: allow
    direction: in
  - port: 443
    proto: tcp
    rule: allow
    direction: out

ufw_custom_rules: []

ufw_applications: []

# Blocklist configuration
ufw_blocklist_enabled: true
ufw_blocklist_url: "https://cdn.jsdelivr.net/gh/duggytuxy/Data-Shield_IPv4_Blocklist@refs/heads/main/prod_data-shield_ipv4_blocklist.txt"
