---
- name: Copy backup nomad job
  ansible.builtin.template:
    src: nomad.operation.hcl
    dest: "/var/tmp/{{ domain }}-operation.nomad"
    owner: root
    group: root
    mode: '0600'
  vars:
    operation: backup
    command: forgejo
    args:
      - dump
      - --config
      - /data/conf/app.ini
    chdir: /var/backup

- name: Run nomad job
  ansible.builtin.include_role:
    name: nomad
    tasks_from: job_run.yml
  vars:
    job_name: "{{ domain }}-operation"
