---
- name: Include actions variables
  ansible.builtin.include_vars: actions.yml

- name: Create first user when email is defined
  community.docker.docker_container:
    name: "{{ domain }}-firstuser"
    image: "forgejo:{{ softwares.forgejo.version }}"
    detach: false
    cleanup: true
    env:
      USER_UID: "1000"
      USER_GID: "1000"
      APP_DATA_PATH: "/data"
      FORGEJO_WORK_DIR: "/data"
    volumes: "{{ forgejo_actions.volumes }}"
    pull: never
    memory: 256M
    command: /usr/local/bin/forgejo admin user create --config /data/conf/app.ini --username {{ lookup('simple-stack-ui', type='secret', key=domain, subkey='admin_user', missing='error') }} --password {{ lookup('simple-stack-ui', type='secret', key=domain, subkey='admin_passwd', missing='error') }} --email {{ lookup('simple-stack-ui', type='secret', key=domain, subkey='admin_email', missing='create', userpass='test@simplestack.demo') }} --admin
  register: forgejo_firstuser
  failed_when: forgejo_firstuser.status >= 1 and "user already exists" not in forgejo_firstuser.msg
  changed_when: forgejo_firstuser.status == 0
  when: software.email is defined
