---
- name: Create default directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: "0755"
  loop:
    - "{{ software_path }}/data"
    - "{{ software_path }}/data/log"
    - "{{ software_path }}/data/custom"
    - "{{ software_path }}/data/conf"
    - "{{ software_path }}/var/backup"
    - "{{ software_path }}/var/log"

- name: Copy script to operate software
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/forgejo-{{ item }}"
    owner: root
    group: root
    mode: '0755'
  loop:
    - backup
    - restore

- name: Create mysql database
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ lookup('simple-stack-ui', type='secret', key=software.dbhost, subkey='passwd', missing='error') }}"
    login_unix_socket: "/data/{{ software.dbhost }}/run/mysqld/mysqld.sock"
    name: "{{ software.dbname | default(service_name[:32]) }}"
    encoding: utf8
    collation: utf8_general_ci
    state: present

- name: Create mysql user
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ lookup('simple-stack-ui', type='secret', key=software.dbhost, subkey='passwd', missing='error') }}"
    login_unix_socket: "/data/{{ software.dbhost }}/run/mysqld/mysqld.sock"
    name: "{{ lookup('simple-stack-ui', type='secret', key=domain, subkey='mysql_user', missing='create', nosymbols=true, length=8) }}"
    host: '%'
    column_case_sensitive: false
    password: "{{ lookup('simple-stack-ui', type='secret', key=domain, subkey='mysql_passwd', missing='create', length=12) }}"
    priv: "{{ service_name[:32] }}.*:ALL"
    state: present

- debug:
    msg: 
- name: Copy default config file
  ansible.builtin.template:
    src: app.ini
    dest: "{{ software_path }}/data/conf/app.ini"
    owner: 1000
    group: 1000
    mode: "0644"

- name: Include actions variables
  ansible.builtin.include_vars: actions.yml

- name: Copy nomad job to destination
  ansible.builtin.template:
    src: nomad.hcl
    dest: "/var/tmp/{{ domain }}.nomad"
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Run nomad job
  ansible.builtin.include_role:
    name: nomad
    tasks_from: job_run.yml

- name: Run nomad job periodic
  ansible.builtin.include_role:
    name: nomad
    tasks_from: job_action.yml
  vars:
    operation: backup
    job_name: "{{ domain }}-periodic"
    periodic: true
    actions: "{{ forgejo_actions }}"

- name: Add first user
  ansible.builtin.include_tasks: first-user.yml
