---
- name: Create default directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: "0755"
  loop:
    - "{{ software_path }}/data"
    - "{{ software_path }}/data/log"
    - "{{ software_path }}/data/custom"
    - "{{ software_path }}/data/conf"
    - "{{ software_path }}/var/backup"
    - "{{ software_path }}/var/log"

- name: Query SRV records
  dig:
    service: "{{ software_vars.dbhost  | replace('-', '') | replace('.', '') }}.default.service.nomad"
  register: service

- name: Create mysql database
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ lookup('community.general.passwordstore', 'mariadb/' + software_vars.dbhost) }}"
    login_host: 172.17.0.1
    login_port: "{{ service.records[0].port }}"
    name: "{{ service_name[:32] }}"
    encoding: utf8
    collation: utf8_general_ci
    state: present

- name: Create mysql user
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ lookup('community.general.passwordstore', 'mariadb/' + software_vars.dbhost) }}"
    login_host: 172.17.0.1
    login_port: "{{ service.records[0].port }}"
    name: "{{ lookup('community.general.passwordstore', 'mariadb/' + domain, missing='create', subkey='user', nosymbols=true, length=8) }}"
    host: '%'
    column_case_sensitive: false
    password: "{{ lookup('community.general.passwordstore', 'mariadb/' + domain, subkey='passwd', missing='create', length=12) }}"
    priv: "{{ service_name[:32] }}.*:ALL"
    state: present

- name: Copy default config file
  ansible.builtin.template:
    src: app.ini
    dest: "{{ software_path }}/data/conf/app.ini"
    owner: 1000
    group: 1000
    mode: "0644"

- name: Copy nomad job to destination
  ansible.builtin.template:
    src: nomad.hcl
    dest: "/var/tmp/{{ domain }}.nomad"
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Run nomad job
  ansible.builtin.include_role:
    name: nomad
    tasks_from: job_run.yml

- name: Add first user
  ansible.builtin.include_tasks: first-user.yml
