---
- name: Backup data
  community.docker.docker_container_exec:
    container: "{{ domain }}-phpfpm-1"
    command: wp-cli db export --allow-root --path=/var/www/html /var/backup/dump.sql
    chdir: /var/www/html
