---
- name: Include actions variables
  ansible.builtin.include_vars: actions.yml

- name: Backup service
  ansible.builtin.include_role:
    name: common
    tasks_from: backup_with_action.yml
  vars:
    backup_actions: "{{ wordpress_actions }}"
