---
- name: Copy backup nomad job
  ansible.builtin.template:
    src: nomad.operation.hcl
    dest: "/var/tmp/{{ domain }}-{{ operation }}.nomad"
    owner: root
    group: root
    mode: '0600'
  vars:
    operation: backup
    command: wp-cli
    args: db export --allow-root --path=/var/www/html /var/backup/dump.sql
    chdir: /var/www/html

- name: Run nomad job
  ansible.builtin.include_role:
    name: nomad
    tasks_from: job_run.yml
  vars:
    job_name: "{{ domain }}-backup"
