---
- name: Install dependencies packages
  ansible.builtin.apt:
    pkg:
      - python3-pymysql
      - php-cli
      - php-common
      - php-iconv
      - php-mbstring
      - php-phar
      - php-mysqli
      - mariadb-client
    state: present
    install_recommends: false
  retries: 10
  delay: 3

- name: Create default /var/www/html/.wp-cli
  become: true
  ansible.builtin.file:
    path: /var/www/.wp-cli
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Download wp-cli
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/bin/wp-cli
    mode: '0755'
