---
- name: Stop nomad job
  ansible.builtin.include_role:
    name: nomad
    tasks_from: job_stop.yml
  vars:
    job_name: "{{ item }}"
  loop:
    - "{{ domain }}"
    - "{{ domain }}-periodic"

- name: Mysql delete database
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ lookup('community.general.passwordstore', 'mariadb/' + software_vars.dbhost) }}"
    login_unix_socket: "/data/{{ software_vars.dbhost }}/run/mysqld/mysqld.sock"
    name: "{{ service_name[:32] }}"
    state: absent

- name: Mysql delete user
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ lookup('community.general.passwordstore', 'mariadb/' + software_vars.dbhost) }}"
    login_unix_socket: "/data/{{ software_vars.dbhost }}/run/mysqld/mysqld.sock"
    name: "{{ lookup('community.general.passwordstore', 'mariadb/' + domain, subkey='user') }}"
    host: '%'
    priv: "{{ service_name[:32] }}.*:ALL"
    state: absent
    column_case_sensitive: false

- name: Remove software directory
  ansible.builtin.file:
    path: "{{ software_path }}"
    state: absent
