---
- name: Create default directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "{{ software_path }}/var/www/html"
    - "{{ software_path }}/var/log/nginx"
    - "{{ software_path }}/var/log/php-fpm"
    - "{{ software_path }}/etc/nginx/sites-enabled"
    - "{{ software_path }}/etc/php-fpm.d"
    - "{{ software_path }}/run/php-fpm"
    - "{{ software_path }}/var/backup"

- name: Create mysql database
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ lookup('simple-stack-ui', type='secret', key=software.dbhost, subkey='passwd', missing='error') }}"
    login_unix_socket: "/data/{{ software.dbhost }}/run/mysqld/mysqld.sock"
    name: "{{ software.dbname | default(service_name[:32]) }}"
    encoding: utf8
    collation: utf8_general_ci
    state: present

- name: Create mysql user
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ lookup('simple-stack-ui', type='secret', key=software.dbhost, subkey='passwd', missing='error') }}"
    login_unix_socket: "/data/{{ software.dbhost }}/run/mysqld/mysqld.sock"
    name: "{{ lookup('simple-stack-ui', type='secret', key=domain, subkey='mysql_user', missing='create', nosymbols=true, length=8, userpass=software.dbuser | default(none)) }}"
    host: '%'
    column_case_sensitive: false
    password: "{{ lookup('simple-stack-ui', type='secret', key=domain, subkey='mysql_passwd', missing='create', length=12) }}"
    priv: "{{ service_name[:32] }}.*:ALL"
    state: present

- name: Install wordpress
  community.docker.docker_container:
    name: "{{ domain }}-install"
    image: "phpfpm-wordpress:{{ softwares.wordpress.version }}"
    detach: false
    cleanup: true
    command: "{{ item }}"
    env:
      HTTP_HOST: "{{ domain }}"
    memory: 256M
    pull: never
    volumes:
      - "{{ software_path }}/var/www/html:/var/www/html"
    mounts:
      - type: bind
        target: /run/mysqld
        source: "/data/{{ software.dbhost }}/run/mysqld"
        read_only: false
    working_dir: /var/www/html
  loop:
    - >
      wp-cli core download
      --allow-root --no-color --path='/var/www/html'
      --locale='fr_FR'
    - >
      wp-cli core config
      --allow-root --no-color --path='/var/www/html'
      --dbname='{{ service_name[:32] }}'
      --dbuser="{{ lookup('simple-stack-ui', type='secret', key=domain, subkey='mysql_user', missing='error') }}"
      --dbpass="{{ lookup('simple-stack-ui', type='secret', key=domain, subkey='mysql_passwd', missing='error') }}"
      --dbhost='localhost:/run/mysqld/mysqld.sock'
      --dbprefix='wp_'
    - >
      wp-cli core install
      --allow-root --no-color --path='/var/www/html'
      --url='{{ domain }}' --title='Wordpress'
      --admin_name="{{ lookup('simple-stack-ui', type='secret', key=domain, subkey='admin_login', missing='create', nosymbols=true, length=8, userpass='admin') }}"
      --admin_email="{{ lookup('simple-stack-ui', type='secret', key=domain, subkey='admin_email', missing='error') }}"
      --admin_password="{{ lookup('simple-stack-ui', type='secret', key=domain, subkey='admin_passwd', missing='create', length=12) }}"
