---
- name: Create default directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "{{ software_path }}/var/www/html"
    - "{{ software_path }}/var/log/nginx"
    - "{{ software_path }}/var/log/php-fpm"
    - "{{ software_path }}/etc/nginx/sites-enabled"
    - "{{ software_path }}/etc/php-fpm.d"
    - "{{ software_path }}/run/php-fpm"
    - "{{ software_path }}/var/backup"

- name: Query SRV records
  dig:
    service: "{{ software_vars.dbhost  | replace('-', '') | replace('.', '') }}.default.service.nomad"
  register: service

- name: Create mysql database
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ lookup('community.general.passwordstore', 'mariadb/' + software_vars.dbhost) }}"
    login_host: 172.17.0.1
    login_port: "{{ service.records[0].port }}"
    name: "{{ service_name[:32] }}"
    encoding: utf8
    collation: utf8_general_ci
    state: present

- name: Create mysql user
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ lookup('community.general.passwordstore', 'mariadb/' + software_vars.dbhost) }}"
    login_host: 172.17.0.1
    login_port: "{{ service.records[0].port }}"
    name: "{{ lookup('community.general.passwordstore', 'mariadb/' + domain, missing='create', subkey='user', nosymbols=true, length=8, userpass=software_vars.userpass | default(none)) }}"
    host: '%'
    column_case_sensitive: false
    password: "{{ lookup('community.general.passwordstore', 'mariadb/' + domain, subkey='passwd', missing='create', length=12, userpass=software_vars.userpass | default(none)) }}"
    priv: "{{ service_name[:32] }}.*:ALL"
    state: present

- name: Install wordpress
  community.docker.docker_container:
    name: "{{ domain }}-install"
    image: "phpfpm-wordpress:{{ ansible_local.software_version['phpfpm-wordpress'] }}"
    detach: false
    cleanup: true
    command: "{{ item }}"
    env:
      HTTP_HOST: "{{ domain }}"
    memory: 256M
    pull: never
    volumes:
      - "{{ software_path }}/var/www/html:/var/www/html"
    mounts:
      - type: bind
        target: /run/mysqld
        source: "/data/{{ software_vars.dbhost }}/run/mysqld"
        read_only: false
    working_dir: /var/www/html
  loop:
    - >
      wp-cli core download
      --allow-root --no-color --path='/var/www/html'
      --locale='fr_FR'
    - >
      wp-cli core config
      --allow-root --no-color --path='/var/www/html'
      --dbname='{{ service_name[:32] }}'
      --dbuser="{{ lookup('community.general.passwordstore', 'mariadb/' + domain, subkey='user') }}"
      --dbpass="{{ lookup('community.general.passwordstore', 'mariadb/' + domain, subkey='passwd') }}"
      --dbhost='localhost:/run/mysqld/mysqld.sock'
      --dbprefix='wp_'
    - >
      wp-cli core install
      --allow-root --no-color --path='/var/www/html'
      --url='{{ domain }}' --title='Wordpress'
      --admin_name="{{ lookup('community.general.passwordstore', 'wordpress/' + domain, missing='create', subkey='user', nosymbols=true, length=8) }}"
      --admin_email="{{ lookup('ansible.builtin.env', 'PROJECT_ADMIN_EMAIL') }}"
      --admin_password="{{ lookup('community.general.passwordstore', 'wordpress/' + domain, missing='create', subkey='passwd', length=12) }}"
