---
- name: Test if config file exists
  ansible.builtin.stat:
    path: "{{ software_path }}/var/www/html/wp-config.php"
  register: stat_result

- name: Install wordpress
  ansible.builtin.include_tasks: install.yml
  when: not stat_result.stat.exists

- name: Copy script to operate software
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/wordpress-{{ item }}"
    owner: root
    group: root
    mode: '0755'
  loop:
    - backup
    - restore

- name: Copy nginx config file
  ansible.builtin.template:
    src: nginx.conf
    dest: "{{ software_path }}/etc/nginx/sites-enabled/default.conf"
    mode: '0644'

- name: Copy phpfpm config file
  ansible.builtin.template:
    src: phpfpm.conf
    dest: "{{ software_path }}/etc/php-fpm.d/www.conf"
    mode: '0644'

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: "{{ software_path }}/var/www/html"
    state: directory
    recurse: true
    owner: www-data
    group: www-data

- name: Copy nomad job
  ansible.builtin.template:
    src: nomad.hcl
    dest: "/var/tmp/{{ domain }}.nomad"
    owner: root
    group: root
    mode: '0600'

- name: Run nomad job
  ansible.builtin.include_role:
    name: nomad
    tasks_from: job_run.yml

- name: Include actions variables
  ansible.builtin.include_vars: actions.yml

- name: Run nomad job periodic
  ansible.builtin.include_role:
    name: nomad
    tasks_from: job_action.yml
  vars:
    operation: backup
    job_name: "{{ domain }}-periodic"
    periodic: true
    actions: "{{ wordpress_actions }}"
