---
- name: Test if config file exists
  ansible.builtin.stat:
    path: "{{ software_path }}/var/www/html/wp-config.php"
  register: stat_result

- name: Install wordpress
  ansible.builtin.include_tasks: install.yml
  when: not stat_result.stat.exists

- name: Copy nginx config file
  ansible.builtin.template:
    src: nginx.conf
    dest: "{{ software_path }}/etc/nginx/sites-enabled/default.conf"
    mode: '0644'

- name: Copy phpfpm config file
  ansible.builtin.template:
    src: phpfpm.conf
    dest: "{{ software_path }}/etc/php-fpm.d/www.conf"
    mode: '0644'
  
- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: "{{ software_path }}/var/www/html"
    state: directory
    recurse: true
    owner: www-data
    group: www-data

- name: Copy nomad job
  ansible.builtin.template:
    src: nomad.hcl
    dest: "/var/tmp/{{ domain }}.nomad"
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Copy periodic nomad job
  ansible.builtin.template:
    src: nomad.periodic.hcl
    dest: "/var/tmp/{{ domain }}-periodic.nomad"
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Run nomad jobs
  ansible.builtin.shell: "nomad job run /var/tmp/{{ item }}.nomad"
  loop:
    - "{{ domain }}"
    - "{{ domain }}-periodic"
