---
- name: Restore data
  community.docker.docker_container_exec:
    container: "{{ domain }}-phpfpm-1"
    command: wp-cli db import --path=/var/www/html /var/backup/dump.sql
    chdir: /var/www/html
