---
- name: Restore wordpress
  community.docker.docker_container:
    name: "{{ domain }}-backup"
    image: "{{ wordpress_phpfpm_image }}"
    auto_remove: true
    detach: false
    command: wp-cli db import --path=/var/www/html /var/backup/dump.sql
    env:
      HTTP_HOST: "{{ wordpress_site.url }}"
    memory: 256M
    pull: never
    user: www-data
    volumes:
      - "/data/{{ domain }}/var/www/html:/var/www/html:ro"
      - "/data/{{ domain }}/var/backup:/var/backup:rw"
      - "/data/mariadb/run/mysqld:/run/mysqld:ro"
    working_dir: /var/www/html
