---
- name: Phpfpm_exporter | Create temporary build directory
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    mode: '0755'
  loop:
    - "{{ build_work_dir }}/download"
    - "{{ build_work_dir }}/{{ upstream_default_arch }}"

- name: Phpfpm_exporter | Download Github release
  ansible.builtin.get_url:
    url: "{{ upstream_file_url }}"
    dest: "{{ build_work_dir }}/download/"
    mode: '0644'
    force: no
  register: download_result

- name: Phpfpm_exporter | Install binary
  ansible.builtin.copy:
    src: "{{ build_work_dir }}/download/{{ image.upstream.binary }}_{{ latest_version }}_{{ image.upstream.os }}_{{ upstream_default_arch }}"
    dest: "/usr/local/bin/{{ image.upstream.binary }}"
    owner: root
    group: root
    mode: '0755'
    remote_src: true

- name: Phpfpm_exporter | Update software version
  software_version:
    software: "{{ image_name }}"
    version: "{{ image_version }}"
    file_path: /etc/ansible/facts.d/software_version.fact

- name: Phpfpm_exporter | Clean up
  ansible.builtin.file:
    path: "{{ build_work_dir }}"
    state: absent
