---
- name: Phpfpm_exporter | Include upstream variables
  ansible.builtin.include_vars: upstream.yml

- name: Phpfpm_exporter | Get binary
  include_tasks: build.yml
  when: ansible_local[image.name] is not defined or ansible_local[image.name] != latest_version
