---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-encoding-pragma
        args:
          - --remove
      - id: check-json
      - id: check-yaml
        exclude: (^ansible/collections)
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
  - repo: local
    hooks:
      - id: ansible-lint
        name: Ansible lint
        language: system
        entry: >-
          bash -c 'cd ansible && ansible-lint --offline
          playbooks/paas/main.yml
          playbooks/saas/main.yml
          playbooks/saas/operate.yml
          playbooks/saas/image-forkable.yml'
        files: ^ansible/
        pass_filenames: false
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
    hooks:
      - id: terraform_fmt
        args:
          - terraform
