---
- name: Mongodb_exporter | Include upstream variables
  ansible.builtin.include_vars: upstream.yml

- name: Mongodb_exporter | Set custom variables
  ansible.builtin.set_fact:
    image_version: "{{ latest_version }}"
    image_name: "{{ image.name }}"
    image_labels: "{{ image.labels }}"
    image_build: "{{ image.build }}"

- name: Mongodb_exporter | Get binary
  include_tasks: build.yml
  when: ansible_local.software_version is not defined or image.name not in ansible_local.software_version or ansible_local.software_version[image.name] != image_version
