---
- name: Install packages
  ansible.builtin.package:
    pkg: "{{ ufw_packages }}"
    state: present
    install_recommends: false
    update_cache: true
    cache_valid_time: 86400
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10

- name: reset firewall
  ufw:
    state: reset
  when: ufw_reset

- name: Configure ufw
  ansible.builtin.include_tasks: config.yml

- name: Start firewall
  community.general.ufw:
    state: "{{ ufw_state }}"
    logging: "{{ ufw_logging }}"

- name: Save custom ufw rules as facts
  ansible.builtin.copy:
    content: "{{ ufw_custom_rules }}"
    dest: /etc/ansible/facts.d/ufw_custom_rules.fact
  when: ufw_custom_rules is defined
