---
- name: Create default directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "{{ software_path }}/var/lib/arangodb3"
    - "{{ software_path }}/var/lib/arangodb3-apps"

- name: Create container
  community.docker.docker_container:
    name: "{{ domain }}-1"
    image: "{{ software }}:{{ ansible_local.software_version[software] }}"
    state: started
    restart_policy: always
    published_ports:
      - 172.17.0.1:0:8529
    labels: "{{ traefik_labels_result.labels }}"
    env:
      ARANGO_ROOT_PASSWORD: "{{ arangodb_root_password }}"
    volumes:
      - "{{ software_path }}/var/lib/arangodb3:/var/lib/arangodb3:rw"
      - "{{ software_path }}/var/lib/arangodb3-apps:/var/lib/arangodb3-apps:rw"
