---
- name: Create default directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "{{ software_path }}/var/lib/arangodb3"
    - "{{ software_path }}/var/lib/arangodb3-apps"
    - "{{ software_path }}/var/backup"
    - "{{ software_path }}/run"
    - "{{ software_path }}/etc/arangodb3"

- name: Copy config file
  ansible.builtin.template:
    src: arangod.conf
    dest: "{{ software_path }}/etc/arangodb3/arangod.conf"
    owner: root
    group: root
    mode: '0600'

- name: Copy nomad job
  ansible.builtin.template:
    src: nomad.hcl
    dest: "/var/tmp/{{ domain }}.nomad"
    owner: root
    group: root
    mode: '0600'

- name: Run nomad job
  ansible.builtin.include_role:
    name: nomad
    tasks_from: job_run.yml

- name: Copy periodic nomad job
  ansible.builtin.template:
    src: nomad.periodic.hcl
    dest: "/var/tmp/{{ domain }}.periodic.nomad"
    owner: root
    group: root
    mode: '0600'
  vars:
    operation: backup
    command: /usr/bin/arangodump
    args: --output-directory /var/backup --server.username root --server.password '{{ lookup('community.general.passwordstore', 'arangodb/' + domain) }}' --server.authentication true --server.endpoint unix:///run/arangodb.sock --overwrite true --all-databases true
    chdir: /var/backup

- name: Run nomad job
  ansible.builtin.shell: "nomad job run /var/tmp/{{ domain }}.periodic.nomad"
