---
image:
  build: false
  upstream:
    source: github
    user: Koenkk
    repo: zigbee2mqtt
    type: archive
    format: tar.gz
    file: VERSION.FORMAT
    os: linux
  labels: {}
  name: zigbee2mqtt
