{
 "title": "DNS Exporter",
 "description": "Dashboard for https://github.com/tykling/dns_exporter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "ip",
    "query": {
     "query": "label_values(dnsexp_dns_query_time_seconds, ip)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(dnsexp_dns_query_time_seconds,job)"
    }
   },
   { "name": "instance", "query": { "query": "label_values(instance)" } },
   {
    "name": "nsid",
    "query": {
     "query": "label_values(dnsexp_dns_query_time_seconds, nsid)"
    }
   },
   {
    "name": "opcode",
    "query": {
     "query": "label_values(dnsexp_dns_query_time_seconds, opcode)"
    }
   },
   {
    "name": "query_name",
    "query": {
     "query": "label_values(dnsexp_dns_query_time_seconds, query_name)"
    }
   },
   {
    "name": "query_type",
    "query": {
     "query": "label_values(dnsexp_dns_query_time_seconds, query_type)"
    }
   },
   {
    "name": "rcode",
    "query": {
     "query": "label_values(dnsexp_dns_query_time_seconds, rcode)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(dnsexp_dns_query_time_seconds, server)"
    }
   },
   {
    "name": "family",
    "query": {
     "query": "label_values(dnsexp_dns_query_time_seconds, family)"
    }
   },
   {
    "name": "reason",
    "label": "Failure reason",
    "query": {
     "query": "label_values(dnsexp_scrape_failures_total,reason)"
    }
   },
   {
    "name": "proxy",
    "query": {
     "query": "label_values(dnsexp_dns_query_time_seconds,proxy)"
    }
   },
   { "name": "protocol", "query": { "query": "label_values(protocol)" } },
   {
    "name": "monitor",
    "query": {
     "query": "label_values(dnsexp_scrape_failures_total,monitor)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Exporter Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DNS Exporter Info",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(dnsexp_build_version_info) by (version,monitor)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape Duration Average by job",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(scrape_duration_seconds{job=~\"dns_exporter\"}) by (job)",
     "legendFormat": "{{monitor}} {{ job }}"
    }
   ]
  },
  {
   "title": "Scrape Duration Average by monitor",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(scrape_duration_seconds{job=~\"dns_exporter\"}) by (monitor)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DNS Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "DNS Response Time by NSID",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(dnsexp_dns_query_time_seconds{instance=~\"$instance\", protocol=~\"$protocol\", ip=~\"$ip\", job=~\"$job\", nsid=~\"$nsid\", opcode=~\"$opcode\", query_name=~\"$query_name\", query_type=~\"$query_type\", rcode=~\"$rcode\", server=~\"$server\", family=~\"$family\", monitor=~\"$monitor\"}) by (nsid)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Response Time by monitor",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(dnsexp_dns_query_time_seconds{instance=~\"$instance\", protocol=~\"$protocol\", ip=~\"$ip\", job=~\"$job\", nsid=~\"$nsid\", opcode=~\"$opcode\", query_name=~\"$query_name\", query_type=~\"$query_type\", rcode=~\"$rcode\", server=~\"$server\", family=~\"$family\", monitor=~\"$monitor\"}) by (monitor)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Response Time by server",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(dnsexp_dns_query_time_seconds{instance=~\"$instance\", protocol=~\"$protocol\", ip=~\"$ip\", job=~\"$job\", nsid=~\"$nsid\", opcode=~\"$opcode\", query_name=~\"$query_name\", query_type=~\"$query_type\", rcode=~\"$rcode\", server=~\"$server\", family=~\"$family\", monitor=~\"$monitor\"}) by (server)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Response Time by protocol",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(dnsexp_dns_query_time_seconds{instance=~\"$instance\", protocol=~\"$protocol\", ip=~\"$ip\", job=~\"$job\", nsid=~\"$nsid\", opcode=~\"$opcode\", query_name=~\"$query_name\", query_type=~\"$query_type\", rcode=~\"$rcode\", server=~\"$server\", family=~\"$family\", monitor=~\"$monitor\"}) by (protocol)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Response Time by proxy",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(dnsexp_dns_query_time_seconds{instance=~\"$instance\", protocol=~\"$protocol\", ip=~\"$ip\", job=~\"$job\", nsid=~\"$nsid\", opcode=~\"$opcode\", query_name=~\"$query_name\", query_type=~\"$query_type\", rcode=~\"$rcode\", server=~\"$server\", family=~\"$family\", monitor=~\"$monitor\"}) by (proxy)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Response Time by family",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(dnsexp_dns_query_time_seconds{instance=~\"$instance\", protocol=~\"$protocol\", ip=~\"$ip\", job=~\"$job\", nsid=~\"$nsid\", opcode=~\"$opcode\", query_name=~\"$query_name\", query_type=~\"$query_type\", rcode=~\"$rcode\", server=~\"$server\", family=~\"$family\", monitor=~\"$monitor\"}) by (family)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Query Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS Query Errors",
     "type": "stat",
     "gridPos": { "h": 11, "w": 3, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(dnsexp_scrape_failures_total{instance=~\"$instance\", protocol=~\"$protocol\", ip=~\"$ip\", job=~\"$job\", nsid=~\"$nsid\", opcode=~\"$opcode\", query_name=~\"$query_name\", query_type=~\"$query_type\", rcode=~\"$rcode\", server=~\"$server\", family=~\"$family\", monitor=~\"$monitor\", reason=~\"$reason\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DNS Query Errors by Reason",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 4, "x": 3, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(dnsexp_scrape_failures_total{instance=~\"$instance\", protocol=~\"$protocol\", ip=~\"$ip\", job=~\"$job\", nsid=~\"$nsid\", opcode=~\"$opcode\", query_name=~\"$query_name\", query_type=~\"$query_type\", rcode=~\"$rcode\", server=~\"$server\", family=~\"$family\", monitor=~\"$monitor\", reason=~\"$reason\"}[$__range])) by (reason) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DNS Query Errors by Server",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 5, "x": 7, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(dnsexp_scrape_failures_total{instance=~\"$instance\", protocol=~\"$protocol\", ip=~\"$ip\", job=~\"$job\", nsid=~\"$nsid\", opcode=~\"$opcode\", query_name=~\"$query_name\", query_type=~\"$query_type\", rcode=~\"$rcode\", server=~\"$server\", family=~\"$family\", monitor=~\"$monitor\", reason=~\"$reason\"}[$__range])) by (server) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DNS Query Errors by Protocol",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 3, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(dnsexp_scrape_failures_total{instance=~\"$instance\", protocol=~\"$protocol\", ip=~\"$ip\", job=~\"$job\", nsid=~\"$nsid\", opcode=~\"$opcode\", query_name=~\"$query_name\", query_type=~\"$query_type\", rcode=~\"$rcode\", server=~\"$server\", family=~\"$family\", monitor=~\"$monitor\", reason=~\"$reason\"}[$__range])) by (protocol) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DNS Query Errors by Monitor",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 5, "x": 15, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(dnsexp_scrape_failures_total{instance=~\"$instance\", protocol=~\"$protocol\", ip=~\"$ip\", job=~\"$job\", nsid=~\"$nsid\", opcode=~\"$opcode\", query_name=~\"$query_name\", query_type=~\"$query_type\", rcode=~\"$rcode\", server=~\"$server\", family=~\"$family\", monitor=~\"$monitor\", reason=~\"$reason\"}[$__range])) by (monitor) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DNS Query Errors by IP Family",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 4, "x": 20, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(dnsexp_scrape_failures_total{instance=~\"$instance\", protocol=~\"$protocol\", ip=~\"$ip\", job=~\"$job\", nsid=~\"$nsid\", opcode=~\"$opcode\", query_name=~\"$query_name\", query_type=~\"$query_type\", rcode=~\"$rcode\", server=~\"$server\", family=~\"$family\", monitor=~\"$monitor\", reason=~\"$reason\"}[$__range])) by (family)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DNS Query Errors by IP Address",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 4, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(dnsexp_scrape_failures_total{instance=~\"$instance\", protocol=~\"$protocol\", ip=~\"$ip\", job=~\"$job\", nsid=~\"$nsid\", opcode=~\"$opcode\", query_name=~\"$query_name\", query_type=~\"$query_type\", rcode=~\"$rcode\", server=~\"$server\", family=~\"$family\", monitor=~\"$monitor\", reason=~\"$reason\"}[$__range])) by (ip)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DNS Query Errors by Query Name",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 4, "x": 4, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(dnsexp_scrape_failures_total{instance=~\"$instance\", protocol=~\"$protocol\", ip=~\"$ip\", job=~\"$job\", nsid=~\"$nsid\", opcode=~\"$opcode\", query_name=~\"$query_name\", query_type=~\"$query_type\", rcode=~\"$rcode\", server=~\"$server\", family=~\"$family\", monitor=~\"$monitor\", reason=~\"$reason\"}[$__range])) by (query_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DNS Query Errors by Query Type",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 4, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(dnsexp_scrape_failures_total{instance=~\"$instance\", protocol=~\"$protocol\", ip=~\"$ip\", job=~\"$job\", nsid=~\"$nsid\", opcode=~\"$opcode\", query_name=~\"$query_name\", query_type=~\"$query_type\", rcode=~\"$rcode\", server=~\"$server\", family=~\"$family\", monitor=~\"$monitor\", reason=~\"$reason\"}[$__range])) by (query_type)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DNS Query Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg_over_time(dnsexp_dns_query_success{instance=~\"$instance\", job=~\"$job\", monitor=~\"$monitor\"}[$__range])",
       "legendFormat": "{{ monitor }} / {{job}} / {{ instance }}"
      }
     ]
    },
    {
     "title": "DNS Query Errors / sec by server and reason",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(dnsexp_scrape_failures_total{instance=~\"$instance\", job=~\"$job\", proxy=~\"$proxy\", reason=~\"$reason\", server=~\"$server\", protocol=~\"$protocol\", monitor=~\"$monitor\"}[$__rate_interval])) by (server,reason)",
       "legendFormat": "{{server}} {{ reason }}"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS Response TTL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Monitored Names",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "dnsexp_dns_response_rr_ttl_seconds{instance=~\"$instance\", protocol=~\"$protocol\", ip=~\"$ip\", job=~\"$job\", nsid=~\"$nsid\", opcode=~\"$opcode\", query_name=~\"$query_name\", query_type=~\"$query_type\", rcode=~\"$rcode\", server=~\"$server\", family=~\"$family\", monitor=~\"$monitor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DNS Response RR TTL",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "avg(dnsexp_dns_response_rr_ttl_seconds{instance=~\"$instance\", protocol=~\"$protocol\", ip=~\"$ip\", job=~\"$job\", nsid=~\"$nsid\", opcode=~\"$opcode\", query_name=~\"$query_name\", query_type=~\"$query_type\", rcode=~\"$rcode\", server=~\"$server\", family=~\"$family\", monitor=~\"$monitor\"}) by (nsid,query_name,query_type)",
       "legendFormat": "{{ server }} {{query_name}} {{ query_type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "WIP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Time Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "sum(rate(dnsexp_dns_responsetime_seconds_bucket{instance=~\"$instance\", protocol=~\"$protocol\", ip=~\"$ip\", job=~\"$job\", nsid=~\"$nsid\", opcode=~\"$opcode\", query_name=~\"$query_name\", query_type=~\"$query_type\", rcode=~\"$rcode\", server=~\"$server\", family=~\"$family\", monitor=~\"$monitor\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}