{
 "title": "Nomad Copy2",
 "description": "Nomad Jobs metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "project", "query": { "query": "label_values(project)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nomad_client_uptime{project=~\"$project\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Failed allocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nomad_client_allocs_failed{instance=~\"$instance\"} ",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Client allocations pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(nomad_client_allocations_pending{instance=~\"$instance\"}) by(project, node_status)",
     "legendFormat": "{{project}} {{node_status}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage Percent from $project / $instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_cpu_total_percent{instance=~\"$instance\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  { "title": "CPU total ticks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Total Ticks from $project / $instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_cpu_total_ticks{instance=~\"$instance\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Memory usage from $project / $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_memory_usage{instance=~\"$instance\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  { "title": "Memory cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Memory Cache from $project / $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_memory_cache{instance=~\"$instance\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  { "title": "RSS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "RSS from $project / $instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_memory_rss{instance=~\"$instance\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  }
 ]
}