---
- name: Create data directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: '0755'
  loop:
    - path: /data/{{ domain }}/config
    - path: /data/{{ domain }}/prometheus
      owner: nobody
      group: nogroup

- name: Copy services configurations files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/data/{{ domain }}/config/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - prometheus.yaml
    - rules.yaml
    - alertmanager-fallback-config.yaml

- name: Template services configurations files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/data/{{ domain }}/config/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - mimir.yaml
    - nginx.conf

- name: Copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "/data/{{ domain }}/docker-compose.yaml"
    owner: root
    group: root
    mode: '0644'

- name: Run `docker compose up`
  community.docker.docker_compose_v2:
    project_src: "/data/{{ domain }}"
  register: output
