---
- name: Backup data
  community.docker.docker_container_exec:
    container: "{{ domain }}"
    argv:
      - /bin/sh
      - "-c"
      - "mariadb-dump --all-databases > /var/backup/dump.sql"
    chdir: /var/backup
