---
- name: Copy restore nomad job
  ansible.builtin.template:
    src: nomad.operation.hcl
    dest: "/var/tmp/{{ domain }}-{{ operation }}.nomad"
    owner: root
    group: root
    mode: '0600'
  vars:
    operation: restore
    command: /usr/bin/mariadb
    args: < /var/backup/dump.sql
    chdir: /var/backup

- name: Run nomad job
  ansible.builtin.include_role:
    name: nomad
    tasks_from: job_run.yml
  vars:
    job_name: "{{ domain }}-restore"
