---
- name: Include actions variables
  ansible.builtin.include_vars: actions.yml

- name: Restore service
  ansible.builtin.include_role:
    name: common
    tasks_from: restore_with_action.yml
  vars:
    restore_actions: "{{ mariadb_actions }}"
