---
- name: Restore data
  community.docker.docker_container_exec:
    container: "{{ domain }}"
    argv:
      - /bin/sh
      - "-c"
      - "mariadb < /var/backup/dump.sql"
    chdir: /var/backup
