---
- name: Create default directory
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - path: "{{ software_path }}/etc/adguard"
      mode: '0755'
    - path: "{{ software_path }}/usr/local/bin/data"
      mode: '0700'
    - path: "{{ software_path }}/usr/local/bin/data/filters"
      mode: '0700'

- name: Copy default config file
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ software_path }}/etc/adguard/config.yml"
    owner: root
    group: root
    mode: "0600"

- name: Copy nomad job to destination
  ansible.builtin.template:
    src: nomad.hcl
    dest: "/var/tmp/{{ domain }}.nomad"
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Run nomad job
  ansible.builtin.include_role:
    name: nomad
    tasks_from: job_run.yml
