---
- name: Check number of host in play
  ansible.builtin.debug:
    msg: "Nomad will be deployed on {{ (ansible_play_hosts | length) }} host{% if (ansible_play_hosts | length) > 1 %}s{% endif %}"

- name: nomad_bind_address
  ansible.builtin.debug:
    msg: "{{ nomad_bind_address }}"

- name: nomad_advertise_address
  ansible.builtin.debug:
    msg: "{{ nomad_advertise_address }}"

- name: nomad_ports
  ansible.builtin.debug:
    msg: "{{ nomad_ports }}"

- name: nomad_servers
  ansible.builtin.debug:
    msg: "{{ nomad_servers }}"

- name: nomad_client_meta_list
  ansible.builtin.debug:
    msg: "{{ nomad_client_meta_list }}"

- name: nomad_servers_advertise_address
  ansible.builtin.debug:
    msg: "{{ nomad_servers_advertise_address }}"

- name: "Nomad | Roles Status"
  ansible.builtin.debug:
    msg: |
      {{ inventory_hostname }} - Nomad role: {{ nomad_node_role }}
    verbosity: 1

- name: "Nomad | Commons tasks | Set-Timezone"
  community.general.timezone:
    name: "{{ nomad_timezone }}"
    hwclock: local
