- name: "Nomad | CNI | Check existing installation"
  ansible.builtin.stat:
    path: /opt/cni/bin/bridge
  register: cni_install

- name: "Nomad | CNI | Create directory for bin"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    recurse: true
    owner: "root"
    group: "root"
  loop:
    - /opt/cni/bin
    - /opt/cni/config
  when: not cni_install.stat.exists

- name: "Nomad | CNI | Retreive GitHub latest version"
  ansible.builtin.uri:
    url: https://api.github.com/repos/containernetworking/plugins/releases/latest
    body_format: json
    return_content: true
  register: tag
  when: not cni_install.stat.exists

- name: "Nomad | CNI | Set fact for CNI version"
  ansible.builtin.set_fact:
    cni_version: "{{ tag.json.tag_name | replace('v', '') }}"
  when: not cni_install.stat.exists

- name: "Nomad | CNI | Display version"
  ansible.builtin.debug:
    msg: "CNI: version {{ cni_version }}"
    verbosity: 1
  when: not cni_install.stat.exists

- name: "Nomad | CNI | Unarchive plugin CNI for {{ architecture | upper }}"
  ansible.builtin.unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/{{ tag.json.tag_name }}/cni-plugins-linux-{{ architecture }}-{{ tag.json.tag_name }}.tgz
    dest: /opt/cni/bin
    remote_src: true
  when: not cni_install.stat.exists

- name: "Nomad | CNI | Ensure br_netfilter is enabled"
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: "Nomad | CNI | Add to sysctl"
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - { name: "net.bridge.bridge-nf-call-arptables", value: "1" }
    - { name: "net.bridge.bridge-nf-call-ip6tables", value: "1" }
    - { name: "net.bridge.bridge-nf-call-iptables", value: "1" }

- name: "Nomad | Network | Conf Netplan for bridge(s)"
  ansible.builtin.template:
    src: 50-bridge.yaml.j2
    dest: /etc/netplan/50-bridge.yaml
    mode: "0600"
  notify: Netplan_apply

- name: "Nomad | Network | Flush handlers"
  ansible.builtin.meta: flush_handlers
