- name: "Nomad | Commons tasks | Install required OS packages"
  ansible.builtin.apt:
    update_cache: true
    pkg: ufw

- name: "Nomad | Firewall | Open ports"
  community.general.ufw:
    rule: allow
    interface: "{{ nomad_cluster_bridge }}"
    direction: "{{ item.direction }}"
    proto: "{{ item.proto }}"
    port: "{{ item.port }}"
  no_log: true
  loop: "{{ nomad_ufw_rules[nomad_node_role] }}"

- name: "Nomad | Firewall | Allow trafic on between nomad and docker0 interface"
  community.general.ufw:
    rule: allow
    interface: "{{ item[0] }}"
    direction: "{{ item[1] }}"
  no_log: true
  loop: "{{ ['nomad', 'docker0'] | product(['in', 'out']) | list }}"
