---
- name: Add configuration
  ansible.builtin.template:
    src: "{{ item }}.hcl.j2"
    dest: "{{ nomad_config_dir }}/{{ item }}.hcl"
    owner: root
    group: root
    mode: '0644'
  loop:
    - nomad
    - client
    - server
    - docker
    - raw_exec
    - raw_exec2
  notify: Nomad restart
