---
- name: Install binary
  ansible.builtin.apt:
    name: "nomad={{ nomad_version }}-1"
    update_cache: yes

- name: Create Nomad logs and data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    group: root
    owner: root
    mode: '0755'
  loop:
    - /var/log/nomad
    - "{{ nomad_data_dir }}"
    - "{{ nomad_data_dir }}/plugins"

- name: Prevent Nomad from being upgraded
  ansible.builtin.dpkg_selections:
    name: nomad
    selection: hold

- name: Systemd daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Unarchive plugin nomad-driver-exec2
  ansible.builtin.unarchive:
    src: "https://releases.hashicorp.com/nomad-driver-exec2/0.1.0/nomad-driver-exec2_0.1.0_linux_{{ upstream_default_arch }}.zip"
    dest: "{{ nomad_data_dir }}/plugins"
    remote_src: yes
