---
# tasks file for install

- name: "Nomad | Commons tasks"
  ansible.builtin.include_tasks: "01_nodes_roles.yml"

- name: "Nomad | Install CNI"
  ansible.builtin.include_tasks: "02_network.yml"

- name: "Nomad | Commons tasks"
  ansible.builtin.include_tasks: "03_commons_tasks.yml"

- name: "Nomad | TLS certs configuration"
  ansible.builtin.include_tasks: "04_tls_certs.yml"

- name: "Nomad | Install"
  ansible.builtin.include_tasks: "05_install.yml"

- name: "Nomad | Global Configuration"
  ansible.builtin.include_tasks: "06_configuration.yml"

- name: "Nomad | Install Nomad Auto Eligibility Node"
  ansible.builtin.include_tasks: "07_autoeligibility.yml"
  when: nomad_mode == 'single'

- name: "Nomad | Change SystemD configuration"
  ansible.builtin.include_tasks: "08_systemd_tuning.yml"

- name: "Nomad | Firewall configuration"
  ansible.builtin.include_tasks: "09_firewall.yml"
  when: nomad_firewall
