---
- name: Build and install debian package
  block:
    - name: Build debian package
      ansible.builtin.include_tasks: build.yml

    - name: Install debian package
      ansible.builtin.apt:
        deb: "/var/cache/apt/archives/{{ deb_file }}.deb"
      notify: Restart loki
  rescue:
    - name: Let's continue the playbook anyway
      debug:
        msg: Rescue debug task

- name: Override config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0600
    owner: root
    group: root
  loop:
    - src: default.j2
      dest: /etc/default/loki
    - src: config.j2
      dest: /etc/loki/config.yaml
  notify: Restart loki
