---
- name: Loki | Include upstream variables
  ansible.builtin.include_vars: upstream.yml

- name: Loki | Set custom variables
  ansible.builtin.set_fact:
    image_version: "{{ latest_version }}"
    image_name: "{{ image.name }}"
    image_labels: "{{ image.labels }}"
    image_build: "{{ image.build }}"
    deb_file: "{{ image.name }}_{{ latest_version }}_{{ image.upstream.os }}_{{ upstream_default_arch }}"

- name: Loki | Get binary
  include_tasks: build.yml
  when: ansible_local.software_version is not defined or image.name not in ansible_local.software_version or ansible_local.software_version[image.name] != image_version

- name: Loki | Create custom directories
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - /etc/loki
    - /var/lib/loki

- name: Loki | Copy templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
    group: root
  loop:
    - src: default.j2
      dest: /etc/default/loki
    - src: config.j2
      dest: /etc/loki/config.yaml
    - src: service.j2
      dest: /etc/systemd/system/loki.service
  notify: Restart loki

- name: Loki | Flush handlers
  ansible.builtin.meta: flush_handlers
