---
- name: Remove systemd timer
  ansible.builtin.include_role:
    name: timer
    tasks_from: remove

- name: Remove containers
  community.docker.docker_container:
    name: "{{ item }}"
    state: absent
  loop:
    - "{{ domain }}-rocketchat-1"
    - "{{ domain }}-mongodb-1"

- name: Remove software directory
  ansible.builtin.file:
    path: "{{ software_path }}"
    state: absent
