---
- name: Create CA TLS
  any_errors_fatal: true
  hosts: "{{ hosts_limit | default('infrastructure') }}"
  gather_facts: false
  strategy: linear
  become: true
  tasks:
    - name: "Create TLS CA"
      ansible.builtin.include_role:
        name: certificate
        tasks_from: ca

- name: Install nomad
  any_errors_fatal: true
  hosts: "{{ hosts_limit | default('infrastructure') }}"
  gather_facts: true
  become: true
  roles:
    - nomad
