---
- name: Create CA TLS
  any_errors_fatal: true
  hosts: infrastructure
  gather_facts: true
  strategy: linear
  become: true
  tasks:
    - name: "Create TLS CA"
      ansible.builtin.include_role:
        name: certificate
        tasks_from: ca
      run_once: true

- name: Install nomad
  any_errors_fatal: true
  hosts: nomad
  gather_facts: true
  become: true
  roles:
    - nomad
