---
- name: Restic | Download package
  ansible.builtin.get_url:
    url: "{{ upstream_file_url }}"
    dest: /tmp
    mode: '0640'

- name: Restic | Extract archive
  ansible.builtin.command:
    cmd: "bzip2 -d /tmp/{{ upstream_file_name }}"

- name: Copy binary to /usr/local/bin
  ansible.builtin.copy:
    src: "/tmp/{{ unarchived_file_name }}"
    dest: "/usr/local/bin/restic"
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

- name: Restic | Clean up
  ansible.builtin.file:
    path: "/tmp/{{ unarchived_file_name }}"
    state: absent

- name: Restic | Backup software version
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      cat << EOF
      "{{ latest_version }}"
      EOF
    dest: "/etc/ansible/facts.d/{{ image.name }}.fact"
    owner: root
    group: root
    mode: '0755'
