---
- name: Restic | Include upstream variables
  ansible.builtin.include_vars: upstream.yml

- name: Restic | Set custom variables
  ansible.builtin.set_fact:
    image_version: "{{ latest_version }}"

- name: Restic | Install latest package
  when: >
    ansible_local.software_version is not defined or
    image.name not in ansible_local.software_version or
    ansible_local.software_version[image.name] != image_version
  block:
    - name: Restic | Download package
      ansible.builtin.get_url:
        url: "{{ upstream_file_url }}"
        dest: /tmp
        mode: '0640'

    - name: Restic | Extract archive
      ansible.builtin.command:
        cmd: "bzip2 -d /tmp/{{ upstream_file_name }}"

    - name: Copy binary to /usr/local/bin
      ansible.builtin.copy:
        src: "/tmp/{{ unarchived_file_name }}"
        dest: "/usr/local/bin/restic"
        owner: root
        group: root
        mode: '0755'
        remote_src: yes

    - name: Restic | Clean up
      ansible.builtin.file:
        path: "/tmp/{{ unarchived_file_name }}"
        state: absent

    - name: Restic | Update software version
      software_version:
        software: "{{ image.name }}"
        version: "{{ latest_version }}"
        file_path: /etc/ansible/facts.d/software_version.fact

- name: Copy script to operate software
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/restic-{{ item }}"
    owner: root
    group: root
    mode: '0755'
  loop:
    - backup
    - restore
