---
- name: Restic | Include upstream variables
  ansible.builtin.include_vars: upstream.yml

- name: Restic | Set custom variables
  ansible.builtin.set_fact:
    image_version: "{{ latest_version }}"

- name: Restic | Get binary
  include_tasks: build.yml
  when: ansible_local[image.name] is not defined or ansible_local[image.name] != latest_version

- name: Copy script to operate software
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/restic-{{ item }}"
    owner: root
    group: root
    mode: '0755'
  loop:
    - backup
    - restore
