---
image:
  build: false
  upstream:
    source: github
    user: RocketChat
    repo: Rocket.Chat
    type: archive
    format: tar.gz
    file: VERSION.FORMAT
    os: linux
  labels: {}
  name: rocketchat
