---
- name: Restart coredns
  ansible.builtin.systemd:
    state: restarted
    name: coredns
    enabled: true

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: systemd-resolved
