---
- name: Install ansible package
  ansible.builtin.pip:
    name: ansible

- name: Install units for ansible-pull
  ansible.builtin.template:
    dest: /etc/systemd/system
    src: "{{ item }}"
    mode: '0644'
  loop:
    - ansible-pull.service
    - ansible-pull.timer
  notify: Daemon reload

- name: Enable ansible-pull timer
  ansible.builtin.service:
    name: ansible-pull.timer
    state: started
    enabled: true
