---
homeassistant_configuration_default:
  http:
    use_x_forwarded_for: true
    trusted_proxies:
      - 172.17.0.0/24

homeassistant_configuration: "{{ software.homeassistant_configuration | default(homeassistant_configuration_default) }}"
