---
homeassistant_devices: "{{ software_vars.devices | default(homeassistant_devices_default) }}"
homeassistant_configuration: "{{ software_vars.configuration | default(homeassistant_configuration_default) }}"
