---
- name: Copy systemd service
  ansible.builtin.template:
    src: service.j2
    dest: "/etc/systemd/system/{{ timer_name }}.service"
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd

- name: Copy systemd timer
  ansible.builtin.template:
    src: timer.j2
    dest: "/etc/systemd/system/{{ timer_name }}.timer"
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd

- name: Enable systemd timer
  ansible.builtin.systemd_service:
    name: "{{ timer_name }}.timer"
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
    scope: "{{ systemd_scope | default('system') }}"
