---
- name: Disable systemd timer
  ansible.builtin.systemd_service:
    name: "{{ timer_name }}.timer"
    state: stopped
    enabled: false
  notify: Reload systemd

- name: Remove systemd timer
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/systemd/system/{{ timer_name }}.timer"
    - "/etc/systemd/system/{{ timer_name }}.service"
  notify: Reload systemd
