---
- name: Operate on an application
  hosts: "{{ hosts_limit | default('infrastructure') }}"
  become: true
  gather_facts: true
  vars_prompt:
    - name: catalog
      prompt: Catalog item
      private: false
    - name: domain
      prompt: Domain name
      private: false
    - name: task
      prompt: Task
      private: false
  vars:
    software_path: "/data/{{ domain }}"
    service_name: "{{ domain | replace('-', '') | replace('.', '') }}"
  pre_tasks:
    - name: Get software variables
      ansible.builtin.set_fact:
        software: "{{ lookup('simple-stack-ui', type='software', key=domain, subkey='', missing='warn') }}"

    - debug:
        msg: "{{ software }}"

  tasks:
    - name: Execute operation
      ansible.builtin.include_role:
        name: "{{ catalog }}"
        tasks_from: "{{ task }}"

  post_tasks:
    - name: Update software version
      ansible.builtin.uri:
        url: "{{ lookup('ansible.builtin.env', 'SIMPLE_STACK_UI_URL') }}/api"
        user: "{{ lookup('ansible.builtin.env', 'SIMPLE_STACK_UI_USER') }}"
        password: "{{ lookup('ansible.builtin.env', 'SIMPLE_STACK_UI_PASSWORD') }}"
        method: POST
        body_format: json
        body:
          schema: softwares_update_version/{{ software.id }}
          data:
            version: "{{ softwares[catalog].version }}"
        force_basic_auth: true
        status_code: 200
      ignore_errors: true
      delegate_to: localhost
      become: false
      when: task == "main"

    - name: Destroy software
      ansible.builtin.uri:
        url: "{{ lookup('ansible.builtin.env', 'SIMPLE_STACK_UI_URL') }}/api"
        user: "{{ lookup('ansible.builtin.env', 'SIMPLE_STACK_UI_USER') }}"
        password: "{{ lookup('ansible.builtin.env', 'SIMPLE_STACK_UI_PASSWORD') }}"
        method: POST
        body_format: json
        body:
          schema: softwares_remove/{{ software.id }}
        force_basic_auth: true
        status_code: 200
      ignore_errors: true
      delegate_to: localhost
      become: false
      when: task == "destroy"