---
- name: Operate on an application
  hosts: infrastructure
  become: true
  gather_facts: true
  vars_prompt:
    - name: software
      prompt: Software name
      private: false
    - name: domain
      prompt: Domain name
      private: false
    - name: task
      prompt: Task
      private: false
  vars:
    software_path: "/data/{{ domain }}"
    service_name: "{{ domain | replace('-', '') | replace('.', '') }}"
    software_vars: "{{ hostvars[inventory_hostname][domain] }}"
  tasks:
    - name: Execute operation
      block:
        - name: Execute operation
          ansible.builtin.include_role:
            name: "{{ software }}"
            tasks_from: "{{ task }}"
      rescue:
        - name: Rescue
          ansible.builtin.debug:
            msg: "This task {{ task }} has a problem or does not exist in this role"
