---
- name: Scan_exporter | Create temporary build directory
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    mode: '0755'
  loop:
    - "{{ build_work_dir }}/download"
    - "{{ build_work_dir }}/{{ upstream_default_arch }}"

- name: Scan_exporter | Download Github release
  ansible.builtin.get_url:
    url: "{{ upstream_file_url }}"
    dest: "{{ build_work_dir }}/download/{{ image.upstream.binary }}"
    mode: '0755'
    force: no
  register: download_result

- name: Scan_exporter | Copy binary
  ansible.builtin.copy:
    src: "{{ build_work_dir }}/download/{{ image.upstream.binary }}"
    dest: "/usr/local/bin/{{ image.upstream.binary }}"
    owner: root
    group: root
    mode: '0755'
    remote_src: true

- name: Scan_exporter | Clean up
  ansible.builtin.file:
    path: "{{ build_work_dir }}"
    state: absent

- name: Scan_exporter | Backup software version
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      cat << EOF
      "{{ latest_version }}"
      EOF
    dest: "/etc/ansible/facts.d/{{ image.name }}.fact"
    owner: root
    group: root
    mode: '0755'
