---
- name: Scan_exporter | Include upstream variables
  ansible.builtin.include_vars: upstream.yml

- name: Scan_exporter | Get binary
  include_tasks: build.yml
  when: ansible_local[image.name] is not defined or ansible_local[image.name] != latest_version

- name: Scan_exporter | Create custom directories
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - /etc/scan_exporter

- name: Scan_exporter | Copy templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0600
    owner: prometheus
    group: prometheus
  loop:
    - src: default.j2
      dest: /etc/default/scan_exporter
    - src: config.yml.j2
      dest: /etc/scan_exporter/config.yml
    - src: service.j2
      dest: /etc/systemd/system/scan_exporter.service
  notify: Restart scan_exporter

- name: Scan_exporter | Flush handlers
  ansible.builtin.meta: flush_handlers
