---
- name: Coredns | Include upstream variables
  ansible.builtin.include_vars: upstream.yml

- name: Coredns | Get binary
  ansible.builtin.include_tasks: build.yml
  when: ansible_local[image.name] is not defined or ansible_local[image.name] != latest_version

- name: Coredns | Create group
  ansible.builtin.group:
    name: coredns
    system: true

- name: Coredns | Create user
  ansible.builtin.user:
    name: coredns
    create_home: false
    system: true

- name: Coredns | Create custom directories
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    state: directory
    mode: '0755'
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  loop:
    - dest: /etc/coredns

- name: Coredns | Override config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0640'
    owner: coredns
    group: coredns
  loop:
    - src: Corefile.j2
      dest: /etc/coredns/Corefile
    - src: service.j2
      dest: /etc/systemd/system/coredns.service
  notify: Restart coredns

- name: Coredns | Create resolved directory
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: '0755'

- name: Coredns | Copy systemd resolved config
  ansible.builtin.copy:
    content: |
      [Resolve]
      DNS=127.0.0.1:1053
      DNSSEC=no
      DNSOverTLS=no
      Domains=~default.service.nomad
      Cache=no
      DNSStubListenerExtra=172.17.0.1:53
    dest: /etc/systemd/resolved.conf.d/coredns.conf
    mode: '0644'
  notify: Restart systemd-resolved
