{
 "title": "NGINX",
 "description": "NGINX Prometheus exporter",
 "tags": [ "web" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "project", "query": { "query": "label_values(project)" } },
   {
    "name": "fqdn",
    "query": {
     "query": "label_values(nginx_up{project=~\"$project\"},fqdn)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "NGINX Status for $fqdn",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "repeat": "fqdn",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nginx_up{fqdn=~\"$fqdn\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Processed connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(nginx_connections_accepted{project=~\"$project\",fqdn=~\"$fqdn\"}[5m])",
       "legendFormat": "{{fqdn}} accepted"
      },
      {
       "expr": "irate(nginx_connections_handled{project=~\"$project\",fqdn=~\"$fqdn\"}[5m])",
       "legendFormat": "{{fqdn}} handled"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nginx_connections_active{project=~\"$project\",fqdn=~\"$fqdn\"}",
       "legendFormat": "{{fqdn}} active"
      },
      {
       "expr": "nginx_connections_reading{project=~\"$project\",fqdn=~\"$fqdn\"}",
       "legendFormat": "{{fqdn}} reading"
      },
      {
       "expr": "nginx_connections_waiting{project=~\"$project\",fqdn=~\"$fqdn\"}",
       "legendFormat": "{{fqdn}} waiting"
      },
      {
       "expr": "nginx_connections_writing{project=~\"$project\",fqdn=~\"$fqdn\"}",
       "legendFormat": "{{fqdn}} writing"
      }
     ]
    },
    {
     "title": "Total requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(nginx_http_requests_total{project=~\"$project\",fqdn=~\"$fqdn\"}[5m])",
       "legendFormat": "{{fqdn}} total requests"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{filename=~\"/data/$fqdn/var/log/nginx/access.log\"}"
    }
   ]
  }
 ]
}