{
 "title": "PHP-FPM",
 "description": "PHP-FPM dashboard",
 "tags": [ "web" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "project", "query": { "query": "label_values(project)" } },
   {
    "name": "fqdn",
    "label": "fqdn",
    "query": {
     "query": "label_values({project=~\"$project\", job=~\"phpfpm_exporter\"},fqdn)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Process Utilisation",
     "type": "gauge",
     "description": "Utilisation of processes based on active/inactive processes",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(sum(phpfpm_active_processes{fqdn=~\"$fqdn\"}) / sum(phpfpm_total_processes{fqdn=~\"$fqdn\"}))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
      }
     ]
    },
    {
     "title": "Max Children reached",
     "type": "stat",
     "description": "How many times was the maximum amount of children reached?",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(phpfpm_max_children_reached{fqdn=~\"$fqdn\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Accepted connections (rpm)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(phpfpm_accepted_connections{fqdn=~\"www.compagnie-aragorn.fr\"}[5m])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "# of containers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(phpfpm_up{fqdn=~\"$fqdn\"} > 0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Queued Requests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(phpfpm_listen_queue{fqdn=~\"$fqdn\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Scrape failures",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(phpfpm_scrape_failures{fqdn=~\"$fqdn\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "# of processes by state",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(fqdn, state) (phpfpm_process_state{fqdn=~\"$fqdn\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}} {{state}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Request Duration by process",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum(phpfpm_process_request_duration{fqdn=~\"$fqdn\"}) by (fqdn, pid_hash)",
       "legendFormat": "{{fqdn}} {{pid_hash}}",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
      }
     ]
    },
    {
     "title": "Queued requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(phpfpm_listen_queue{fqdn=~\"$fqdn\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}} # of requests",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Requests per process",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(phpfpm_process_requests{fqdn=~\"$fqdn\"}[5m])) by (fqdn, pid_hash)",
       "legendFormat": "{{fqdn}} {{pid_hash}}",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
      }
     ]
    },
    {
     "title": "# of Active & Idle processes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(phpfpm_active_processes{fqdn=~\"$fqdn\"}) by (fqdn)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}} # of active processes",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(phpfpm_idle_processes{fqdn=~\"$fqdn\"}) by (fqdn)",
       "legendFormat": "{{fqdn}} # of idle processes"
      },
      {
       "expr": "sum(phpfpm_total_processes{fqdn=~\"$fqdn\"}) by (fqdn)",
       "legendFormat": "{{fqdn}} # of total processes"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "{job=\"phpfpm\", filename=~\"/data/$fqdn/var/log/php-fpm/php-fpm.access.log\"} |= ``"
    }
   ]
  }
 ]
}