---
forgejo_db_name: "{{ service_name[:32] }}"
forgejo_db_user: "{{ service_name[:32] }}"
forgejo_db_password: "{{ lookup('password', '/tmp/forgejo_db_password chars=ascii_letters,digits,hexdigits length=15') }}"

forgejo_admin_login: forgejo
forgejo_admin_password: "{{ lookup('ansible.builtin.env', 'PROJECT_ADMIN_PASSWORD') }}"
forgejo_admin_email: "{{ lookup('ansible.builtin.env', 'PROJECT_ADMIN_EMAIL') }}"
