---
- name: Prometheus | Include upstream variables
  ansible.builtin.include_vars: upstream.yml

- name: Prometheus | Get binary
  include_tasks: build.yml
  when: ansible_local[image.name] is not defined or ansible_local[image.name] != latest_version

- name: Prometheus | Create prometheus group
  ansible.builtin.group:
    name: prometheus
    system: true

- name: Prometheus | Create prometheus user
  ansible.builtin.user:
    name: prometheus
    create_home: false
    system: true

- name: Prometheus | Create custom directories
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  loop:
    - dest: /etc/prometheus
    - dest: /var/lib/prometheus
      owner: prometheus
      group: prometheus

- name: Prometheus | Copy templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
    owner: prometheus
    group: prometheus
  loop:
    - src: default.j2
      dest: /etc/default/prometheus
    - src: config.j2
      dest: /etc/prometheus/prometheus.yml
    - src: service.j2
      dest: /etc/systemd/system/prometheus.service
  notify: Restart prometheus

- name: Prometheus | Flush handlers
  ansible.builtin.meta: flush_handlers
