---
# vars file for install

# Architecture replacement
nomad_architecture_map:
  i386: "386"
  x86_64: amd64
  aarch64: arm64
  armv7l: armv7
  armv6l: armv6

nomad_architecture: "{{ nomad_architecture_map[ansible_architecture] }}"
