---
# vars file for install

# Architecture replacement
architecture_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv6l: 'armv6'

architecture: "{{ architecture_map[ansible_architecture] | default(ansible_architecture) }}"

nomad_ufw_rules:
  client:
    - { proto: "tcp", port: "4646", direction: "in" }
    - { proto: "tcp", port: "4646", direction: "out" }
    - { proto: "tcp", port: "4647", direction: "in" }
    - { proto: "tcp", port: "4647", direction: "out" }
    - { proto: "tcp", port: "20000:32000", direction: "in" }
    - { proto: "tcp", port: "20000:32000", direction: "out" }
    - { proto: "udp", port: "20000:32000", direction: "in" }
    - { proto: "udp", port: "20000:32000", direction: "out" }
  server:
    - { proto: "tcp", port: "4646", direction: "in" }
    - { proto: "tcp", port: "4646", direction: "out" }
    - { proto: "tcp", port: "4647", direction: "in" }
    - { proto: "tcp", port: "4647", direction: "out" }
    - { proto: "tcp", port: "4648", direction: "in" }
    - { proto: "tcp", port: "4648", direction: "out" }
    - { proto: "udp", port: "4648", direction: "in" }
    - { proto: "udp", port: "4648", direction: "out" }
  both:
    - { proto: "tcp", port: "4646", direction: "in" }
    - { proto: "tcp", port: "4646", direction: "out" }
    - { proto: "tcp", port: "4647", direction: "in" }
    - { proto: "tcp", port: "4647", direction: "out" }
    - { proto: "tcp", port: "4648", direction: "in" }
    - { proto: "tcp", port: "4648", direction: "out" }
    - { proto: "udp", port: "4648", direction: "in" }
    - { proto: "udp", port: "4648", direction: "out" }
    - { proto: "tcp", port: "20000:32000", direction: "in" }
    - { proto: "tcp", port: "20000:32000", direction: "out" }
    - { proto: "udp", port: "20000:32000", direction: "in" }
    - { proto: "udp", port: "20000:32000", direction: "out" }
