#!/bin/sh
set +eu

echo "Add few debian packages"
apt-get -qq update && apt-get install -yqq mariadb-client sudo --no-install-recommends

echo "Enable maintenance mode..."
sudo -u www-data php occ maintenance:mode --on

echo "Decompress data..."
tar -xzf /var/backup/data.tgz -C /var/www/html

echo "Import mysql database..."
/usr/bin/mariadb -u${DBUSER} -p${DBPASS} ${1} < /var/backup/dump.sql

echo "Disable maintenance mode..."
sudo -u www-data php occ maintenance:mode --off
