#!/bin/bash
set +eu

apt-get -qq update && apt-get install -qq dnsutils -y

echo "Get dynmic port and service address..."
read -r _ _ PORT ADDR <<< "$(dig SRV ${1}-mongodb.default.service.nomad +short)"

echo "Backup mongodb database..."
/opt/bitnami/mongodb/bin/mongodump --host="${ADDR}:${PORT}" --out /var/backup
