---
- name: Set up multiple authorized keys
  ansible.posix.authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ ssh_custom_users }}"
    exclusive: true
  when: ssh_user_public_keys is defined
