---
image:
  build: false
  upstream:
    source: github
    user: Dolibarr
    repo: dolibarr
    type: archive
    format: tar.gz
    file: VERSION.FORMAT
    os: linux
  labels: {}
  name: dolibarr
