---
- name: Initialize default directory
  ansible.builtin.file:
    path: "{{ software_path }}/repo"
    state: absent
  when: nodejs_config.initialize

- name: Create default directory
  ansible.builtin.file:
    path: "{{ software_path }}/repo"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"

- name: Git checkout
  ansible.builtin.git:
    repo: "{{ nodejs_config.repo }}"
    dest: "{{ software_path }}/repo"
    version: "{{ nodejs_config.version }}"

- name: Install packages based on package.json
  community.docker.docker_container:
    name: "{{ domain }}-npm-install"
    image: "{{ software }}:{{ ansible_local.software_version[software] }}"
    detach: false
    cleanup: true
    command: npm install
    memory: 256M
    pull: never
    user: nodejs
    volumes:
      - "{{ software_path }}/repo:/var/lib/repo:rw"
    working_dir: /var/lib/repo

- name: Create container
  community.docker.docker_container:
    name: "{{ domain }}-1"
    image: "{{ software }}:{{ ansible_local.software_version[software] }}"
    state: started
    restart_policy: always
    command: node index.js
    published_ports:
      - 172.17.0.1:0:3000
    labels: "{{ traefik_labels_result.labels }}"
    volumes:
      - "{{ software_path }}/repo:/var/lib/repo:rw"
    working_dir: /var/lib/repo
    pull: never
