---
- name: Daemon reload
  listen: Restart promtail
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart promtail
  listen: Restart promtail
  ansible.builtin.service:
    name: promtail
    state: restarted
    enabled: true
