# General
nomad_job_dir: "/var/tmp"

nomad_http_ip: "127.0.0.1"

# TLS
nomad_tls_host_certificate_dir: "/etc/ssl/simplestack"
nomad_tls_cert_server: "{{ nomad_region }}-server-nomad.pem"
nomad_tls_privatekey_server: "{{ nomad_region }}-server-nomad.key"
nomad_tls_ca_pubkey: "simplestack-ca.pem"
