---
- name: Create default directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 33
    group: 33
    mode: '0755'
  loop:
    - "{{ software_path }}/var/www/html/documents"
    - "{{ software_path }}/var/www/html/custom"

# - name: Query SRV records
#   dig:
#     service: "{{ software.dbhost | replace('-', '') | replace('.', '') }}.default.service.nomad"
#   register: service

- name: Create mysql database
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ lookup('simple-stack-ui', type='secret', key=software.dbhost, subkey='passwd', missing='error') }}"
    login_unix_socket: "/data/{{ software.dbhost }}/run/mysqld/mysqld.sock"
    name: "{{ software.dbname | default(service_name[:32]) }}"
    encoding: utf8
    collation: utf8_general_ci
    state: present

- name: Create mysql user
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ lookup('simple-stack-ui', type='secret', key=software.dbhost, subkey='passwd', missing='error') }}"
    login_unix_socket: "/data/{{ software.dbhost }}/run/mysqld/mysqld.sock"
    name: "{{ lookup('simple-stack-ui', type='secret', key=domain, subkey='mysql_user', missing='create', nosymbols=true, length=8, userpass=software.dbuser | default(none)) }}"
    host: '%'
    column_case_sensitive: false
    password: "{{ lookup('simple-stack-ui', type='secret', key=domain, subkey='mysql_passwd', missing='create', length=12) }}"
    priv: "{{ service_name[:32] }}.*:ALL"
    state: present
