---
- name: Include actions variables
  ansible.builtin.include_vars: actions.yml

- name: Run nomad restore job
  ansible.builtin.include_role:
    name: nomad
    tasks_from: job_action.yml
  vars:
    operation: restore
    job_name: "{{ domain }}-restore"
    periodic: false
    actions: "{{ dolibarr_actions }}"
