---
- name: Remove containers
  community.docker.docker_container:
    name: "{{ domain }}-1"
    state: absent

- name: Remove software directory
  ansible.builtin.file:
    path: "/data/{{ domain }}"
    state: absent
