---
- name: Create default directory
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: '0755'
  loop:
    - path: "{{ software_path }}/app"
    - path: "{{ software_path }}/app/data"
      owner: 1001
      group: 1001
    - path: "{{ software_path }}/app/data/log"
      owner: 1001
      group: 1001

- name: Copy default config file
  ansible.builtin.template:
    src: configuration.yaml.j2
    dest: "{{ software_path }}/app/data/configuration.yaml"
    owner: 1001
    group: 1001
    mode: "0644"

- name: Create container
  community.docker.docker_container:
    name: "{{ domain }}-1"
    image: "koenkk/zigbee2mqtt:{{ ansible_local.software_version[software] }}"
    state: started
    restart_policy: always
    published_ports:
      - 172.17.0.1:0:8080
    labels: "{{ traefik_labels_result.labels }}"
    user: "1001:1001"
    groups:
      - dialout
    devices:
      - "{{ zigbee2mqtt_config.device }}:{{ zigbee2mqtt_config.device }}"
    volumes:
      - "{{ software_path }}/app/data:/app/data:rw"
      - "/run/udev:/run/udev:ro"
