# fail2ban jails for Traefik access logs

{% if fail2ban_wp_login_enabled %}
[traefik-wp-login]
enabled              = true
filter               = traefik-wp-login
logpath              = {{ fail2ban_traefik_access_log }}
maxretry             = {{ fail2ban_wp_login_maxretry }}
findtime             = {{ fail2ban_wp_login_findtime }}
bantime              = {{ fail2ban_wp_login_bantime }}
bantime.increment    = {{ fail2ban_bantime_increment | lower }}
bantime.multipliers  = {{ fail2ban_bantime_multipliers }}
bantime.maxtime      = {{ fail2ban_bantime_maxtime }}
bantime.overalljails = {{ fail2ban_bantime_overalljails | lower }}
ignoreip             = {{ fail2ban_ignoreip | join(' ') }}
action               = ufw-conntrack
{% endif %}

{% if fail2ban_404_enabled %}
[traefik-404]
enabled              = true
filter               = traefik-404
logpath              = {{ fail2ban_traefik_access_log }}
maxretry             = {{ fail2ban_404_maxretry }}
findtime             = {{ fail2ban_404_findtime }}
bantime              = {{ fail2ban_404_bantime }}
bantime.increment    = {{ fail2ban_bantime_increment | lower }}
bantime.multipliers  = {{ fail2ban_bantime_multipliers }}
bantime.maxtime      = {{ fail2ban_bantime_maxtime }}
bantime.overalljails = {{ fail2ban_bantime_overalljails | lower }}
ignoreip             = {{ fail2ban_ignoreip | join(' ') }}
action               = ufw-conntrack
{% endif %}

{% if fail2ban_ratelimit_enabled %}
[traefik-ratelimit]
enabled              = true
filter               = traefik-ratelimit
logpath              = {{ fail2ban_traefik_access_log }}
maxretry             = {{ fail2ban_ratelimit_maxretry }}
findtime             = {{ fail2ban_ratelimit_findtime }}
bantime              = {{ fail2ban_ratelimit_bantime }}
bantime.increment    = {{ fail2ban_bantime_increment | lower }}
bantime.multipliers  = {{ fail2ban_bantime_multipliers }}
bantime.maxtime      = {{ fail2ban_bantime_maxtime }}
bantime.overalljails = {{ fail2ban_bantime_overalljails | lower }}
ignoreip             = {{ fail2ban_ignoreip | join(' ') }}
action               = ufw-conntrack
{% endif %}
