- name: "Nomad operate | Stop job"
  ansible.builtin.command: "/usr/bin/nomad job stop {{ nomad_job_name }}"
  environment:
    NOMAD_ADDR: "https://{{ nomad_http_ip }}:4646"
    NOMAD_TOKEN: "{{ lookup('community.general.passwordstore', 'nomad/' + inventory_hostname + '/nomad_management_token') }}"
    NOMAD_CLIENT_CERT: "{{ nomad_tls_host_certificate_dir }}/{{ nomad_tls_cert_server }}"
    NOMAD_CLIENT_KEY: "{{ nomad_tls_host_certificate_dir }}/{{ nomad_tls_privatekey_server }}"
    NOMAD_CACERT: "{{ nomad_tls_host_certificate_dir }}/{{ nomad_tls_ca_pubkey }}"
  register: nomad_job_stop
  changed_when: nomad_job_stop.rc != 0
