---
wordpress_db_name: "{{ (domain | replace('-', '') | replace('.', ''))[:32] }}"
wordpress_db_password: "{{ ansible_local[service_name].wordpress_db_password | default(lookup('password', '/tmp/wordpress_db_password chars=ascii_letters,digits,hexdigits length=15')) }}"
wordpress_db_user: "{{ ansible_local[service_name].wordpress_db_user | default((domain | replace('-', '') | replace('.', ''))[:32]) }}"

wordpress_admin_login: admin
wordpress_admin_password: "{{ software_secrets.admin_password | default(lookup('password', '/tmp/wordpress_admin_password chars=ascii_letters,digits,hexdigits length=8')) }}"
wordpress_admin_email: "{{ software_secrets.admin_login | default('admin@test.com') }}"

wordpress_nginx_image: nginx:1.26.2
wordpress_phpfpm_image: phpfpm-wordpress:8.3.13

wordpress_site:
  name: wordpress
  dbname: "{{ wordpress_db_name }}"
  dbuser: "{{ wordpress_db_user }}"
  dbpass: "{{ wordpress_db_password }}"
  path: "/var/www/html"
  url: "{{ domain }}"
  title: wordpress
  locale: fr_FR
  admin_name: "{{ wordpress_admin_login }}"
  admin_email: "{{ wordpress_admin_email }}"
  admin_password: "{{ wordpress_admin_password }}"

wordpress_traefik_labels: |
  {{
    {
      "traefik.enable": "true",
      "traefik.http.routers.{}.tls".format(service_name): "true",
      "traefik.http.routers.{}.tls.certresolver".format(service_name): "myresolver",
      "traefik.http.routers.{}.tls.options".format(service_name): "mintls12@file",
      "traefik.http.routers.{}.entrypoints".format(service_name): "https",
      "traefik.http.routers.{}.rule".format(service_name): "Host(`{}`)".format(domain),
      "traefik.http.middlewares.{}.redirectscheme.scheme".format(service_name): "https",
      "traefik.http.middlewares.{}.redirectscheme.permanent".format(service_name): "true",
      "traefik.http.middlewares.{}-headers.headers.customResponseHeaders.Strict-Transport-Security".format(service_name): "max-age=63072000",
      "traefik.http.middlewares.{}-headers.headers.frameDeny".format(service_name): "true",
      "traefik.http.middlewares.{}-headers.headers.browserXssFilter".format(service_name): "true",
      "traefik.http.middlewares.{}-headers.headers.contentTypeNosniff".format(service_name): "true",
      "traefik.http.middlewares.{}-headers.headers.stsIncludeSubdomains".format(service_name): "true",
      "traefik.http.middlewares.{}-headers.headers.stsPreload".format(service_name): "true",
      "traefik.http.middlewares.{}-headers.headers.stsSeconds".format(service_name): "31536000",
      "traefik.http.middlewares.{}-headers.headers.forceSTSHeader".format(service_name): "true",
      "traefik.http.middlewares.{}-headers.headers.accessControlMaxAge".format(service_name): "15552000",
      "traefik.http.middlewares.{}-headers.headers.customFrameOptionsValue".format(service_name): "SAMEORIGIN"
    }
  }}

wordpress_scale:
  nginx:
    - id: 1
      state: started
      php_socket: 2
  phpfpm:
    - id: 1
      state: started
    - id: 2
      state: started
