---
wordpress_db_name: "{{ (domain | replace('-', '') | replace('.', ''))[:32] }}"
wordpress_db_password: "{{ ansible_local[service_name].wordpress_db_password | default(lookup('password', '/tmp/wordpress_db_password chars=ascii_letters,digits,hexdigits length=15')) }}"
wordpress_db_user: "{{ ansible_local[service_name].wordpress_db_user | default((domain | replace('-', '') | replace('.', ''))[:32]) }}"

wordpress_admin_login: admin
wordpress_admin_password: "{{ software_secrets.admin_password | default(lookup('password', '/tmp/wordpress_admin_password chars=ascii_letters,digits,hexdigits length=8')) }}"
wordpress_admin_email: "{{ software_secrets.admin_login | default('admin@test.com') }}"

wordpress_nginx_image: nginx:1.26.2
wordpress_phpfpm_image: phpfpm-wordpress:8.3.13

wordpress_site:
  name: wordpress
  dbname: "{{ wordpress_db_name }}"
  dbuser: "{{ wordpress_db_user }}"
  dbpass: "{{ wordpress_db_password }}"
  path: "/var/www/html"
  url: "{{ domain }}"
  title: wordpress
  locale: fr_FR
  admin_name: "{{ wordpress_admin_login }}"
  admin_email: "{{ wordpress_admin_email }}"
  admin_password: "{{ wordpress_admin_password }}"

wordpress_scale:
  nginx:
    - id: 1
      state: started
      php_socket: 2
  phpfpm:
    - id: 1
      state: started
    - id: 2
      state: started
