---
- name: Create default directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "{{ software_path }}"
    - "{{ software_path }}/letsencrypt"
    - /var/log/traefik

- name: Copy config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ software_path }}/{{ item }}"
    owner: root
    group: root
    mode: '0600'
  loop:
    - traefik.toml
    - traefik_tls.toml

- name: Copy nomad job to destination
  ansible.builtin.template:
    src: nomad.hcl
    dest: "/var/tmp/{{ domain }}.nomad"
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Run nomad job
  ansible.builtin.include_role:
    name: nomad
    tasks_from: job_run.yml
