---
- name: Daemon reload
  listen: Restart systemd_exporter
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart systemd_exporter
  listen: Restart systemd_exporter
  ansible.builtin.service:
    name: systemd_exporter
    state: restarted
    enabled: true
