---
- name: Include upstream variables
  ansible.builtin.include_vars: upstream.yml

- name: Set custom variables
  ansible.builtin.set_fact:
    image_version: "{{ latest_version }}"
    image_name: "{{ image.name }}"
    image_labels: "{{ image.labels }}"
    image_build: "{{ image.build }}"

- name: End playbook if no new version
  ansible.builtin.meta: end_host
  when: softwares[image.name] is defined and softwares[image.name] == image_version

- name: Download Github release
  ansible.builtin.get_url:
    url: "{{ upstream_file_url }}"
    dest: "{{ build_work_dir }}/download/"
    mode: '0644'
    force: no
  register: download_result

- name: Unarchive GitHub release
  ansible.builtin.unarchive:
    src: "{{ build_work_dir }}/download/{{ upstream_file_name }}"
    dest: "{{ build_work_dir }}/download"
    remote_src: true
  when: download_result.changed

- name: Find binary
  ansible.builtin.include_role:
    name: upstream
    tasks_from: find-binary
  loop:
    - "{{ image.upstream.binary }}"

- name: Copy dockerfile
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: "{{ path }}/Dockerfile"
    mode: '0644'
