---
- name: Create default directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ software_path }}/etc/caddy"

- name: Copy default config file
  ansible.builtin.template:
    src: Caddyfile
    dest: "{{ software_path }}/etc/caddy/Caddyfile"
    owner: root
    group: root
    mode: "0644"

- name: Create container
  community.docker.docker_container:
    name: "{{ domain }}-{{ item.id }}"
    image: "{{ software }}:{{ ansible_local.software_version[software] }}"
    state: "{{ item.state }}"
    recreate: true
    restart_policy: always
    published_ports:
      - 172.17.0.1:0:8080
    labels: "{{ traefik_labels_result.labels }}"
    mounts:
      - type: bind
        target: /etc/caddy
        source: "{{ software_path }}/etc/caddy"
        read_only: true
    pull: never
  loop: "{{ caddy_scale.caddy }}"
