---
postgresql_actions:
  environment: |
    POSTGRESQL_PASSWORD = "{{ lookup('simple-stack-ui', type='secret', key=domain, subkey='passwd', missing='error') }}"
  volumes:
    - "{{ software_path }}/bitnami/postgresql:/bitnami/postgresql:ro"
    - "{{ software_path }}/var/backup:/var/backup:rw"
    - "{{ software_path }}/tmp:/tmp:rw"
    - "/usr/local/bin/postgresql-backup:/usr/local/bin/postgresql-backup:ro"
    - "/usr/local/bin/postgresql-restore:/usr/local/bin/postgresql-restore:ro"
  image: "bitnami/postgresql:{{ softwares.postgresql.version }}"
  user: postgres
