{
 "title": "Maison",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Energy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{entity=\"sensor.n0_buanderie_enery_consumption_puissance\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_data_rate_kib_per_s{entity!~\"sensor.4g_ax56_ef00_vitesse_de_telechargement\"}",
     "legendFormat": "Déscendant"
    },
    {
     "expr": "homeassistant_sensor_data_rate_kib_per_s{entity!~\"sensor.4g_ax56_ef00_vitesse_de_telechargement_montant\"}",
     "legendFormat": "Montant"
    }
   ]
  },
  {
   "title": "Internet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "expr": "homeassistant_sensor_data_rate_kib_per_s{entity!~\"sensor.4g_ax56_ef00_vitesse_de_telechargement\"}",
       "legendFormat": "Upload"
      },
      {
       "expr": "homeassistant_sensor_data_rate_kib_per_s{entity!~\"sensor.4g_ax56_ef00_vitesse_de_telechargement_montant\"}",
       "legendFormat": "Download"
      }
     ]
    }
   ]
  },
  { "title": "Weather", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_temperature_celsius",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_humidity_percent",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_pressure_hpa",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Lights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Illuminance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "lux" } },
     "targets": [
      {
       "expr": "homeassistant_sensor_illuminance_lx",
       "legendFormat": "{{friendly_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Battery",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "homeassistant_sensor_battery_percent",
       "legendFormat": "{{friendly_name}}"
      }
     ]
    }
   ]
  }
 ]
}