---
mariadb_actions:
  environment:
  volumes:
    - "{{ software_path }}/root:/root:rw"
    - "{{ software_path }}/run/mysqld:/run/mysqld:rw"
    - "{{ software_path }}/var/backup:/var/backup:rw"
    - "/usr/local/bin/mariadb-backup:/usr/local/bin/mariadb-backup:ro"
    - "/usr/local/bin/mariadb-restore:/usr/local/bin/mariadb-restore:ro"
  image: "mariadb:{{ softwares.mariadb.version }}"
