---
- name: Unattended-upgrades | Install required packages for autoupdate
  ansible.builtin.apt:
    name: unattended-upgrades
    cache_valid_time: 86400

- name: Unattended-upgrades | Configure unattended upgrades
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    mode: '0644'
  loop:
    - 50unattended-upgrades
    - 20auto-upgrades
