---
- name: Create default directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ software_path }}/var/www/html"

- name: Copy default index file
  ansible.builtin.copy:
    src: index.html
    dest: "{{ software_path }}/var/www/html/index.html"
    owner: root
    group: root
    mode: "0644"

- name: Copy nomad job
  ansible.builtin.template:
    src: nomad.hcl
    dest: "/var/tmp/{{ domain }}.nomad"
    owner: root
    group: root
    mode: '0600'

- name: Run nomad job
  ansible.builtin.shell: "nomad job run /var/tmp/{{ domain }}.nomad"
