---
- name: Create default directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "/data/{{ domain }}/var/www/html"

- name: Copy default index file
  ansible.builtin.copy:
    src: index.html
    dest: "/data/{{ domain }}/var/www/html/index.html"
    owner: root
    group: root
    mode: "0644"

- name: Create container
  community.docker.docker_container:
    name: "{{ domain }}-1"
    image: "nginx:{{ nginx_version }}"
    state: started
    recreate: false
    restart_policy: always
    published_ports:
      - 172.17.0.1:0:80
    labels: "{{ nginx_traefik_labels }}"
    mounts:
      - type: bind
        target: /var/www/html
        source: "/data/{{ domain }}/var/www/html"
        read_only: true
    pull: never
