---
nextcloud_actions:
  environment: |
    DBUSER = "{{ lookup('simple-stack-ui', type='secret', key=domain, subkey='mysql_user', missing='error') }}"
    DBPASS = "{{ lookup('simple-stack-ui', type='secret', key=domain, subkey='mysql_passwd', missing='error') }}"
  volumes:
    - "{{ software_path }}/var/www/html:/var/www/html:rw"
    - "{{ software_path }}/var/backup:/var/backup:rw"
    - "/data/{{ software.dbhost }}/run/mysqld:/var/run/mysqld:ro"
    - "/data/{{ software.dbhost }}/root:/root:ro"
    - "/usr/local/bin/nextcloud-backup:/usr/local/bin/nextcloud-backup:ro"
    - "/usr/local/bin/nextcloud-restore:/usr/local/bin/nextcloud-restore:ro"
  image: "nextcloud:{{ softwares.nextcloud.version }}"
