---
image:
  build: true
  upstream:
    source: github
    user: nextcloud
    repo: server
    type: archive
    format: tar.gz
    file: VERSION.FORMAT
    os: linux
  labels: {}
  name: nextcloud
