---
- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    enabled: true

- name: Reload fail2ban
  ansible.builtin.command: fail2ban-client reload
  changed_when: true
