---
- name: Blackbox_exporter | Include upstream variables
  ansible.builtin.include_vars: upstream.yml

- name: Blackbox_exporter | Get binary
  include_tasks: build.yml
  when: ansible_local[image.name] is not defined or ansible_local[image.name] != latest_version

- name: Blackbox_exporter | Create custom directories
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - /etc/blackbox_exporter

- name: Blackbox_exporter | Copy templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0600
    owner: prometheus
    group: prometheus
  loop:
    - src: default.j2
      dest: /etc/default/blackbox_exporter
    - src: config.j2
      dest: /etc/blackbox_exporter/config.yaml
    - src: service.j2
      dest: /etc/systemd/system/blackbox_exporter.service
  notify: Restart blackbox_exporter

- name: Blackbox_exporter | Flush handlers
  ansible.builtin.meta: flush_handlers
