---
- name: Build and install debian package
  block:
    - name: Build debian package
      ansible.builtin.include_tasks: build.yml

    - name: Install debian package
      ansible.builtin.apt:
        deb: "/var/cache/apt/archives/{{ deb_file }}.deb"
      notify: Restart blackbox_exporter
  rescue:
    - name: Let's continue the playbook anyway
      debug:
        msg: Rescue debug task

- name: Override config file
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0600
    owner: prometheus
    group: prometheus
  loop:
    - src: default.j2
      dest: /etc/default/blackbox_exporter
  notify: Restart blackbox_exporter
