---
arangodb_actions:
  environment: |
    ARANGO_RANDOM_ROOT_PASSWORD = "{{ lookup('simple-stack-ui', type='secret', key=domain, subkey='root_passwd', missing='error') }}"
  volumes:
    - "{{ software_path }}/var/lib/arangodb3:/var/lib/arangodb3:rw"
    - "{{ software_path }}/var/lib/arangodb3-apps:/var/lib/arangodb3-apps:rw"
    - "{{ software_path }}/var/backup:/var/backup:rw"
    - "{{ software_path }}/run:/run:rw"
    - "/usr/local/bin/arangodb-backup:/usr/local/bin/arangodb-backup:ro"
    - "/usr/local/bin/arangodb-restore:/usr/local/bin/arangodb-restore:ro"
  image: "arangodb:{{ softwares.arangodb.version }}"
