---
image:
  build: false
  upstream:
    source: github
    user: arangodb
    repo: arangodb
    type: archive
    format: tar.gz
    file: VERSION.FORMAT
    os: linux
  labels: {}
  name: arangodb

arangodb_root_password: "{{ lookup('ansible.builtin.env', 'PROJECT_ADMIN_PASSWORD') | default('Oops!') }}"
