---
image:
  build: false
  upstream:
    source: github
    user: arangodb
    repo: arangodb
    type: archive
    format: tar.gz
    file: VERSION.FORMAT
    os: linux
  labels: {}
  name: arangodb
