#!/bin/sh
set +eu

cd /var/backup

echo "Unarchive backup..."
tar -xzf data.tgz

echo "Import mysql database..."
/usr/bin/mariadb ${1} < /var/backup/dump.sql

echo "Restore data"
rsync -av --delete --exclude "data.tgz" --exclude "dump.sql" . /data
