[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[api]
  dashboard = true
  insecure = true
  
[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.http]
      [entryPoints.http.http.redirections]
        [entryPoints.http.http.redirections.entrypoint]
          to = "https"
          scheme = "https"
  [entryPoints.metrics]
    address = ":8081"
  [entryPoints.https]
    address = ":443"

[serversTransport]
  insecureSkipVerify = true

[metrics]
  [metrics.prometheus]
    buckets = [0.1,0.3,1.2,5.0]
    addEntryPointsLabels = true
    addServicesLabels = true
    entryPoint = "metrics"

[log]
  level = "WARN"
  filePath = "/var/log/traefik/traefik.log"

[accessLog]
  filePath = "/var/log/traefik/traefik-access.log"

[certificatesResolvers.myresolver.acme]
  email = "{{ traefik_email }}"
  storage = "/etc/traefik/letsencrypt/acme.json"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "http"

[providers]
  [providers.nomad]
    refreshInterval = "30s"
    watch = true
    prefix = "traefik"
    exposedByDefault = false
  [providers.nomad.endpoint]
    address = "https://{{ hostvars[nomad_primary_master_node | default(software.instance)]['ansible_ens3']['ipv4']['address'] | default('127.0.0.1') }}:4646"
    token = "{{ lookup('simple-stack-ui', type='secret', key=inventory_hostname, subkey='nomad_traefik_token', missing='error') }}"
  [providers.nomad.endpoint.tls]
    ca = "/etc/ssl/simplestack/simplestack-ca.pem"
    cert = "/etc/ssl/simplestack/{{ software.instance }}-dc1-client-nomad.pem"
    key = "/etc/ssl/simplestack/{{ software.instance }}-dc1-client-nomad.key"

  [providers.file]
    filename = "/etc/traefik/traefik_tls.toml"
