---
# handlers file for install

- name: Update_cache
  ansible.builtin.apt:
    update_cache: true

- name: Netplan_apply
  ansible.builtin.command: "netplan apply"
  async: 45
  poll: 0
  register: netplan_apply
  changed_when: netplan_apply.ansible_job_id != 0

- name: Nomad_restart
  ansible.builtin.systemd_service:
    name: nomad
    state: restarted
    enabled: true
    daemon_reload: true

- name: Systemd_reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Nomad_s3_jobs
  ansible.builtin.command: "/usr/bin/nomad job run {{ item }}"
  args:
    chdir: "{{ nomad_job_files_dir }}"
  environment:
    NOMAD_ADDR: "https://{{ nomad_http_ip }}:4646"
    NOMAD_TOKEN: "{{ lookup('simple-stack-ui', type='secret', key=inventory_hostname, subkey='nomad_management_token', missing='error') }}"
    NOMAD_CLIENT_CERT: "{{ nomad_tls_host_certificate_dir }}/{{ nomad_tls_cert_server }}"
    NOMAD_CLIENT_KEY: "{{ nomad_tls_host_certificate_dir }}/{{ nomad_tls_privatekey_server }}"
    NOMAD_CACERT: "{{ nomad_tls_host_certificate_dir }}/{{ nomad_tls_ca_pubkey }}"
  register: nomad_job_start
  failed_when: nomad_job_start.rc >= 2
  changed_when:
    - '"error" in nomad_job_start.stdout'
    - nomad_job_start.rc >= 2
  loop:
    - "plugin-s3-controller.hcl"
    - "plugin-s3-node.hcl"
