---
- name: Mysqld_exporter | Include upstream variables
  ansible.builtin.include_vars: upstream.yml

- name: Mysqld_exporter | Set custom variables
  ansible.builtin.set_fact:
    image_version: "{{ latest_version }}"
    image_name: "{{ image.name }}"
    image_labels: "{{ image.labels }}"
    image_build: "{{ image.build }}"

- name: Mysqld_exporter | Get binary
  include_tasks: build.yml
  when: ansible_local[image.name] is not defined or ansible_local[image.name] != latest_version
