---
- name: Remove containers
  community.docker.docker_container:
    name: "{{ domain }}-1"
    state: absent
  ignore_errors: true

- name: Remove software directory
  ansible.builtin.file:
    path: "{{ software_path }}"
    state: absent
