---
- name: Daemon reload
  listen: Restart prometheus
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart prometheus
  listen: Restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted
    enabled: true
