---
- name: Daemon reload
  listen: Restart node_exporter
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart node_exporter
  listen: Restart node_exporter
  ansible.builtin.service:
    name: node_exporter
    state: restarted
    enabled: true
