---
- name: Create default directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: '0755'
  loop:
    - path: "{{ software_path }}"
    - path: "{{ software_path }}/mosquitto/config"
      owner: 1883
      group: 1883
    - path: "{{ software_path }}/mosquitto/log"
      owner: 1883
      group: 1883

- name: Copy configuration file
  ansible.builtin.template:
    src: mosquitto-no-auth.conf.j2
    dest: "{{ software_path }}/mosquitto/config/mosquitto.conf"
    owner: 1883
    group: 1883
    mode: '0644'

- name: Copy nomad job to destination
  ansible.builtin.template:
    src: nomad.hcl
    dest: "/var/tmp/{{ domain }}.nomad"
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Run nomad job
  ansible.builtin.include_role:
    name: nomad
    tasks_from: job_run.yml
