---
- name: Include upstream variables
  ansible.builtin.include_vars: upstream.yml

- name: Set custom variables
  ansible.builtin.set_fact:
    image_version: "{{ latest_version }}"
    image_name: "{{ image.name }}"
    image_labels: "{{ image.labels }}"
    image_build: "{{ image.build }}"

- name: End playbook if no new version
  ansible.builtin.meta: end_host
  when: softwares[image.name] is defined and softwares[image.name] == image_version
